"""Opens PRs on the Gaia registry with batched skill candidates."""

import json
import os
import subprocess
from datetime import datetime


def open_proposal_pr(
    candidates: list[dict],
    source_name: str,
    owner: str = "mbtiongson1",
    repo: str = "gaia-skill-tree",
) -> str:
    """Open a PR with proposed skills. Uses gh CLI."""
    if not candidates:
        print("No candidates to propose.")
        return ""

    date = datetime.now().strftime("%Y-%m-%d")
    branch = f"bot/{source_name}/{date}"
    title = f"[bot] Add {len(candidates)} skills from {source_name} ({date})"

    table_rows = []
    for c in candidates:
        score = ""
        if c.get("evidence"):
            notes = c["evidence"][0].get("notes", "")
            if "score:" in notes:
                score = notes.split("score:")[1].strip().split(".")[0]
        table_rows.append(f"| {c['id']} | {c['name']} | {c['type']} | {score} |")

    body = f"""## Bot Skill Proposal

**Source:** {source_name}
**Date:** {date}
**Candidates:** {len(candidates)}

### Proposed Skills

| ID | Name | Type | Evidence Score |
|---|---|---|---|
{chr(10).join(table_rows)}

---
Auto-generated by Gaia crawler bot.
"""

    output_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..", "proposals")
    os.makedirs(output_dir, exist_ok=True)

    output_file = os.path.join(output_dir, f"{source_name}-{date}.json")
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(candidates, f, indent=2)

    print(f"Wrote {len(candidates)} candidates to {output_file}")
    print(f"PR title: {title}")
    print(f"PR branch: {branch}")
    print(f"\nTo open PR manually:")
    print(f"  git checkout -b {branch}")
    print(f"  git add proposals/")
    print(f"  git commit -m \"{title}\"")
    print(f"  gh pr create --title \"{title}\" --body '<body>' --label bot-proposal --label source:{source_name}")

    return output_file


def open_evidence_upgrade_pr(
    upgrades: list[dict],
    source_name: str,
    owner: str = "mbtiongson1",
    repo: str = "gaia-skill-tree",
) -> str:
    """Open a PR proposing evidence upgrades to existing skills."""
    if not upgrades:
        print("No evidence upgrades to propose.")
        return ""

    date = datetime.now().strftime("%Y-%m-%d")
    branch = f"bot/{source_name}/{date}"
    title = f"[bot] Upgrade evidence for {len(upgrades)} skills from {source_name} ({date})"

    table_rows = []
    for u in upgrades:
        ev = u.get("evidence", {})
        table_rows.append(
            f"| {u['skill_id']} | {ev.get('class', '')} | {ev.get('source', '')[:60]} |"
        )

    body = f"""## Evidence Upgrade Proposal

**Source:** {source_name}
**Date:** {date}
**Upgrades:** {len(upgrades)}

### Proposed Evidence Additions

| Skill ID | Class | Source |
|---|---|---|
{chr(10).join(table_rows)}

---
Auto-generated by Gaia papers crawler bot.
"""

    output_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..", "proposals")
    os.makedirs(output_dir, exist_ok=True)

    output_file = os.path.join(output_dir, f"{source_name}-{date}.json")
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(upgrades, f, indent=2)

    print(f"Wrote {len(upgrades)} evidence upgrades to {output_file}")
    print(f"PR title: {title}")
    print(f"PR branch: {branch}")
    print(f"\nTo open PR manually:")
    print(f"  git checkout -b {branch}")
    print(f"  git add proposals/")
    print(f"  git commit -m \"{title}\"")
    print(f"  gh pr create --title \"{title}\" --body '<body>' --label bot-proposal --label evidence-upgrade --label source:{source_name}")

    return output_file
