#!/usr/bin/env python3
"""Generate ``docs/css/tokens.css`` from ``registry/gaia.json``.

Stage 1 — Foundation. Single source of truth for tier and rank colour
tokens is ``registry/gaia.json``'s ``meta`` block. Every UI surface
(JS, CSS, generated profile pages, OG cards, sampler pages) reads the
emitted CSS custom properties — no hex codes hard-coded outside
``gaia.json``.

Emitted tokens
--------------
Tier (one block per tier in ``typeColors``)::

    --tier-<name>          /* hex */
    --tier-<name>-rgb      /* "R, G, B" triplet */
    --tier-<name>-bg       /* rgba(..., .12) translucent fill */
    --tier-<name>-border   /* rgba(..., .35) hairline */
    --tier-<name>-symbol   /* '○' / '◇' / '◉' / '◆' content() value */

Rank (one block per ``"N★"`` key in ``levelColors``, where N ∈ 0..6)::

    --rank-<N>             /* hex */
    --rank-<N>-bg          /* rgba(..., .12-.22) */
    --rank-<N>-border      /* rgba(..., .35-.55) */

Legacy aliases (single-source-of-truth bridge for code that predates the
``--tier-*`` canonicalization)::

    --basic / --extra / --unique / --ultimate  →  var(--tier-<name>)

Wired into
----------
* ``scripts/syncDocsGraphAssets.py`` — regenerated every registry update.
* ``scripts/build_docs.py --check`` — fails CI if tokens.css is stale.

Idempotent: running this script twice on the same input produces the
exact same bytes. Stable key ordering by tier insertion order, then by
ascending star value 0..6.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GAIA_JSON = ROOT / "registry" / "gaia.json"
TOKENS_CSS = ROOT / "docs" / "css" / "tokens.css"

# Background / border opacity defaults if a colour entry only provides ``hex``.
DEFAULT_BG_ALPHA = 0.12
DEFAULT_BORDER_ALPHA = 0.35


def _hex_to_rgb_triplet(hex_str: str) -> tuple[int, int, int]:
    """``#38bdf8`` → ``(56, 189, 248)``."""
    h = hex_str.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) != 6:
        raise ValueError(f"Cannot parse hex colour: {hex_str!r}")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _rgb_str(rgb: tuple[int, int, int]) -> str:
    return f"{rgb[0]}, {rgb[1]}, {rgb[2]}"


def _star_int(level_key: str) -> int:
    """``"3★"`` → ``3``. Strict: requires a star suffix in the input."""
    if not level_key:
        return -1
    digits = "".join(c for c in level_key if c.isdigit())
    return int(digits) if digits else -1


def _emit_tier_block(name: str, color: dict, symbol: str | None) -> list[str]:
    """Emit five lines for a single tier."""
    hex_val = color.get("hex")
    rgb_raw = color.get("rgb")
    if not hex_val:
        raise ValueError(f"typeColors[{name!r}] missing 'hex'")
    if rgb_raw:
        rgb_triplet = _rgb_str(tuple(int(p.strip()) for p in str(rgb_raw).split(",")))
    else:
        rgb_triplet = _rgb_str(_hex_to_rgb_triplet(hex_val))
    bg = f"rgba({rgb_triplet}, {DEFAULT_BG_ALPHA})"
    border = f"rgba({rgb_triplet}, {DEFAULT_BORDER_ALPHA})"
    lines = [
        f"  --tier-{name}: {hex_val};",
        f"  --tier-{name}-rgb: {rgb_triplet};",
        f"  --tier-{name}-bg: {bg};",
        f"  --tier-{name}-border: {border};",
    ]
    if symbol:
        # Quote with single quotes; escape any embedded single quotes.
        escaped = symbol.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  --tier-{name}-symbol: '{escaped}';")
    return lines


def _emit_rank_block(star: int, color: dict) -> list[str]:
    """Emit three lines for a single rank star value."""
    hex_val = color.get("hex")
    if not hex_val:
        raise ValueError(f"levelColors[{star}★] missing 'hex'")
    # bg / border may be provided directly; otherwise derive from hex.
    rgb_triplet = _rgb_str(_hex_to_rgb_triplet(hex_val))
    bg = color.get("bg") or f"rgba({rgb_triplet}, {DEFAULT_BG_ALPHA})"
    border = color.get("border") or f"rgba({rgb_triplet}, {DEFAULT_BORDER_ALPHA})"
    return [
        f"  --rank-{star}: {hex_val};",
        f"  --rank-{star}-bg: {bg};",
        f"  --rank-{star}-border: {border};",
    ]


def build_tokens_css(gaia: dict) -> str:
    """Render the canonical tokens.css text from a gaia.json dict."""
    meta = gaia.get("meta") or {}
    type_colors = meta.get("typeColors") or {}
    type_symbols = meta.get("typeSymbols") or {}
    level_colors = meta.get("levelColors") or {}
    version = gaia.get("version", "unknown")
    generated_at = gaia.get("generatedAt", "")

    body: list[str] = []
    body.append("/*")
    body.append(" * tokens.css — generated by scripts/generateCssTokens.py.")
    body.append(" * Source of truth: registry/gaia.json meta block.")
    body.append(" * DO NOT EDIT BY HAND. Run scripts/generateCssTokens.py to refresh.")
    body.append(f" * version={version} generatedAt={generated_at}")
    body.append(" */")
    body.append("")
    body.append(":root {")
    body.append("  /* ── Tier tokens ──────────────────────────────────────────── */")

    # Stable tier order (insertion order from JSON).
    for name, color in type_colors.items():
        body.append(f"  /* tier: {name} */")
        body.extend(_emit_tier_block(name, color, type_symbols.get(name)))

    body.append("")
    body.append("  /* ── Rank tokens (0★ → 6★) ───────────────────────────────── */")

    # Stable rank order by star value (0..6 ascending). Skip entries that
    # don't parse as an integer star to avoid surprises.
    parsed_ranks: list[tuple[int, dict]] = []
    for key, color in level_colors.items():
        n = _star_int(key)
        if n >= 0:
            parsed_ranks.append((n, color))
    parsed_ranks.sort(key=lambda t: t[0])
    for star, color in parsed_ranks:
        body.append(f"  /* rank: {star}★ */")
        body.extend(_emit_rank_block(star, color))

    body.append("")
    body.append("  /* ── Legacy short aliases ─────────────────────────────────── */")
    body.append("  /* Bridge for code that predates the --tier-* canonicalization. */")
    body.append("  /* Single source of truth stays in gaia.json.meta.typeColors. */")
    for name in type_colors.keys():
        body.append(f"  --{name}: var(--tier-{name});")

    body.append("}")
    body.append("")
    return "\n".join(body)


def load_gaia(path: Path) -> dict:
    if not path.exists():
        print(f"ERROR: {path} not found", file=sys.stderr)
        raise SystemExit(1)
    return json.loads(path.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail with exit code 1 if tokens.css is stale.",
    )
    parser.add_argument(
        "--gaia",
        default=str(GAIA_JSON),
        help="Path to registry/gaia.json (default: %(default)s).",
    )
    parser.add_argument(
        "--out",
        default=str(TOKENS_CSS),
        help="Output path (default: %(default)s).",
    )
    args = parser.parse_args(argv)

    gaia_path = Path(args.gaia)
    out_path = Path(args.out)

    gaia = load_gaia(gaia_path)
    rendered = build_tokens_css(gaia)

    if args.check:
        if not out_path.exists():
            print(
                f"ERROR: {out_path.relative_to(ROOT)} missing. "
                "Run `python scripts/generateCssTokens.py` to create it.",
                file=sys.stderr,
            )
            return 1
        current = out_path.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"ERROR: {out_path.relative_to(ROOT)} is stale. "
                "Run `python scripts/generateCssTokens.py` to refresh.",
                file=sys.stderr,
            )
            return 1
        print(f"tokens.css is up to date ({out_path.relative_to(ROOT)}).")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote {out_path.relative_to(ROOT)} ({len(rendered)} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
